import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ViewProvider } from "../components/window-layouts/ViewContext";
import MainWindow from "../components/window-layouts/MainWindow";
import { QueryProvider } from "@/context/QueryProvider";
import { ItemsProvider } from "./inventory/components/item-registration/context/ItemsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ItemsProvider>
            <ViewProvider>
              {" "}
              <MainWindow>{children}</MainWindow>
            </ViewProvider>
          </ItemsProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
